name: lint_pr
on: [push, pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: 'src'
        exclude: 'lib'
        clangFormatVersion: 12
